# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-21 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=120)),
                ('issue', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('severity', models.CharField(max_length=120)),
                ('reported', models.CharField(max_length=120)),
                ('owner', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('comments', models.CharField(max_length=120)),
            ],
        ),
    ]
