# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-21 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='date',
            field=models.DateTimeField(max_length=120),
        ),
    ]
