# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-21 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200221_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracker',
            new_name='Tracker_app',
        ),
    ]
