# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-21 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20200221_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker_app',
            name='date',
            field=models.CharField(max_length=120),
        ),
    ]
