# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-21 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20200221_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker_app',
            old_name='reported',
            new_name='reporter',
        ),
    ]
