# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20200221_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker_app',
            name='occ',
            field=models.CharField(default='SOME STRING', max_length=120),
        ),
    ]
