# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_tracker_app_occ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker_app',
            name='occ',
            field=models.CharField(max_length=120),
        ),
    ]
