# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-21 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20200221_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracker_incidents',
            new_name='Tracker_incident',
        ),
    ]
