# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20200221_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker_incident',
            name='date',
            field=models.DateField(),
        ),
    ]
